# Generated by Django 4.2.7 on 2023-11-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='No_Image', upload_to='fotos/'),
        ),
    ]
