# Generated by Django 4.2.7 on 2023-11-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0002_alter_categoria_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.FileField(upload_to='fotos/'),
        ),
    ]
