# Generated by Django 5.0.3 on 2024-05-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0002_alter_reserva_codigo_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='reservas',
            field=models.BooleanField(default=False),
        ),
    ]
