# Generated by Django 5.0.3 on 2024-05-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0002_reserva_usuario_venta_usuario_compraentrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compraentrada',
            old_name='cantidad_entradas',
            new_name='entrada_general',
        ),
        migrations.AddField(
            model_name='compraentrada',
            name='entrada_vip',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compraentrada',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
