# Generated by Django 4.2.7 on 2023-11-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0002_evento_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(default='No_Image', upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='No_Image', upload_to='fotos/')),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Oasis.galeria')),
            ],
        ),
    ]
