# Generated by Django 5.0.3 on 2024-05-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0003_rename_cantidad_entradas_compraentrada_entrada_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='entradas_disponibles',
            field=models.IntegerField(default=500),
        ),
    ]
