# Generated by Django 5.0.1 on 2024-01-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0003_alter_categoria_foto'),
    ]

    operations = [
    ]
