# Generated by Django 4.2.7 on 2023-11-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0003_galeria_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(default='No_Image', upload_to='fotos/'),
        ),
    ]
