# Generated by Django 5.0.3 on 2024-05-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0004_evento_entradas_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='entradas_disponibles',
            field=models.IntegerField(default=models.IntegerField(default=500)),
        ),
    ]
