# Generated by Django 5.0.1 on 2024-01-30 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0004_merge_0002_usuario_clave_0003_alter_categoria_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='fotos_productos/default.png', upload_to='fotos_productos/'),
        ),
    ]
