# Generated by Django 5.0.3 on 2024-05-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0005_pedido_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='detalles',
            new_name='comentario',
        ),
    ]
