# Generated by Django 5.0.1 on 2024-01-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0005_alter_categoria_foto_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(default='No_Image', upload_to='fotos/'),
        ),
    ]
