# Generated by Django 4.2.6 on 2024-01-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0006_alter_categoria_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(default='fotos_categoria/default.png', upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='fotos_eventos/default.png', upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(default='fotos_galeria/default.png', upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='foto',
            field=models.ImageField(default='fotos_carpetas/default.png', upload_to='fotos/'),
        ),
    ]
