# Generated by Django 5.0.1 on 2024-01-31 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0007_alter_categoria_foto_alter_evento_foto_and_more'),
    ]

    operations = [
    ]
