# Generated by Django 5.0.3 on 2024-05-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0008_alter_historialpedido_estado_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpedido',
            name='comentario',
        ),
    ]
