# Generated by Django 5.0.1 on 2024-01-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0009_estado_rol_alter_usuario_estado_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(default='Img_categorias/default.png', upload_to='Img_categorias/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='Img_eventos/default.png', upload_to='Img_eventos/'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(default='Img_galeria/default.png', upload_to='Img_galeria/'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='foto',
            field=models.ImageField(default='Img_carpeta/default.png', upload_to='Img_carpeta/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='Img_productos/default.png', upload_to='Img_productos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='Img_usuarios/default.png', upload_to='Img_usuarios/'),
        ),
    ]
