# Generated by Django 5.0.3 on 2024-05-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0009_remove_historialpedido_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En preparación', 'En preparacion'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='En preparación', max_length=14),
        ),
    ]
