# Generated by Django 5.0.3 on 2024-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0010_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Eliminado', 'Eliminado')], default='Activo', max_length=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='motivo_eliminacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
