# Generated by Django 5.0.1 on 2024-02-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0010_alter_categoria_foto_alter_evento_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Bartender'), (3, 'Mesero'), (4, 'Cliente')], default=4),
        ),
    ]
