# Generated by Django 5.0.1 on 2024-02-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0011_alter_usuario_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
