# Generated by Django 5.0.1 on 2024-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0013_alter_usuario_estado_delete_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Bloqueado')], default=1),
        ),
    ]
