# Generated by Django 5.0.1 on 2024-02-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0014_alter_usuario_estado'),
    ]

    operations = [
    ]
