# Generated by Django 5.0.3 on 2024-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0017_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aforo',
            field=models.IntegerField(default=500),
        ),
    ]
