# Generated by Django 5.0.3 on 2024-04-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0018_evento_aforo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio_entrada',
            field=models.IntegerField(default=50000),
        ),
    ]
