# Generated by Django 5.0.3 on 2024-04-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0021_alter_mesa_estado_reserva_alter_mesa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(default=5),
        ),
    ]
