# Generated by Django 5.0.3 on 2024-04-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0022_mesa_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='codigo_qr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Disponible', 'Disponible')], default='Disponible', max_length=10),
        ),
    ]
