# Generated by Django 5.0.3 on 2024-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0023_alter_mesa_codigo_qr_alter_mesa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio_vip',
            field=models.IntegerField(default=75000),
        ),
    ]
